/**
 * §9.6 — AUTO-GENERATED marker helper.
 *
 * Lightweight composer that prepends the canonical marker block to a
 * codegen output file before writing it to `src/`. The deterministic
 * slot/layout grammar from §8.4 is a separate, larger effort tracked
 * by `BLUEPRINT--CODEGEN-MICROTASK-RUNNER`; this helper covers the
 * common case where the runner already produced a single string per
 * target file and the only post-process step needed is the marker.
 */
import { mkdir, writeFile, readdir, readFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
const DEFAULT_PREFIX = '// ';
/** The marker the validator (PROTO--AUTO-GENERATED-MARKER) looks for. */
export const AUTO_GENERATED_MARKER_TAG = 'AUTO-GENERATED — DO NOT EDIT';
export function buildAutoGeneratedMarker(input) {
    const p = input.commentPrefix ?? DEFAULT_PREFIX;
    return [
        `${p}${AUTO_GENERATED_MARKER_TAG}`,
        `${p}Source: ${input.manifestPath}`,
        `${p}Regenerate: npm run msp:run-task ${input.feature}`,
        '',
    ].join('\n');
}
export async function composeWithMarker(input) {
    await mkdir(dirname(input.outputPath), { recursive: true });
    const header = buildAutoGeneratedMarker(input);
    await writeFile(input.outputPath, header + input.body, 'utf8');
}
export function bodyContainsMarker(body) {
    return body.includes(AUTO_GENERATED_MARKER_TAG);
}
/** Validator for PROTO--AUTO-GENERATED-MARKER */
export async function predicate(ctx) {
    const violations = [];
    async function* walk(dir) {
        let entries;
        try {
            entries = await readdir(dir, { withFileTypes: true });
        }
        catch {
            return;
        }
        for (const entry of entries) {
            const p = join(dir, entry.name);
            if (entry.isDirectory()) {
                if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === '.git')
                    continue;
                yield* walk(p);
            }
            else if (entry.isFile()) {
                yield p;
            }
        }
    }
    // Scan all packages/*/src
    const packagesDir = join(ctx.repoRoot, 'packages');
    let packages = [];
    try {
        packages = await readdir(packagesDir);
    }
    catch {
        // fallback or ignore
    }
    for (const pkg of packages) {
        const srcDir = join(packagesDir, pkg, 'src');
        for await (const file of walk(srcDir)) {
            let body;
            try {
                body = await readFile(file, 'utf8');
            }
            catch {
                continue;
            }
            if (body.includes(AUTO_GENERATED_MARKER_TAG)) {
                const lines = body.split('\n');
                // Check if the marker is at the very beginning (ignoring potential shebang or BOM)
                const markerLineIdx = lines.findIndex((l) => l.includes(AUTO_GENERATED_MARKER_TAG));
                if (markerLineIdx > 5)
                    continue; // Heuristic: if it's not in the first 5 lines, it's likely a reference, not a marker
                const line1 = lines[markerLineIdx];
                const line2 = lines[markerLineIdx + 1] ?? '';
                const line3 = lines[markerLineIdx + 2] ?? '';
                const prefix = line1.slice(0, line1.indexOf(AUTO_GENERATED_MARKER_TAG));
                if (!line2.includes('Source: ')) {
                    violations.push({
                        message: `File ${relative(ctx.repoRoot, file)} has malformed marker: missing 'Source:' on line 2`,
                        severity: 'warning',
                    });
                }
                if (!line3.includes('Regenerate: npm run msp:run-task ')) {
                    violations.push({
                        message: `File ${relative(ctx.repoRoot, file)} has malformed marker: missing 'Regenerate: npm run msp:run-task' on line 3`,
                        severity: 'warning',
                    });
                }
            }
        }
    }
    return { ok: violations.length === 0, violations };
}
