/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenOptions {
  path: string
  pageCacheMb?: number
  readOnly?: boolean
  vectorDim?: number
}
export interface NodeInput {
  id?: string
  labels: Array<string>
  props?: any
  embedding?: Array<number>
  lang?: string
  validFrom?: string
  causedBy?: string
  ttl?: number
  /** Vector collection to route `embedding` into. Defaults to `default`. */
  collection?: string
}
export interface LogicalClock {
  time: number
  peerId: string
}
export interface NodeOutput {
  id: string
  labels: Array<string>
  props: any
  impact?: number
  embedding?: Array<number>
  lang?: string
  validFrom: string
  validTo?: string
  causedBy?: string
  expiresAt?: string
  clock: LogicalClock
  /**
   * Which vector collection this node's embedding lives in (None = default).
   * Persisted in the WAL `Event::Node` so replay rebuilds the right space.
   */
  collection?: string
}
export interface EdgeInput {
  id?: string
  from: string
  to: string
  rel: string
  props?: any
  validFrom?: string
  supersede?: boolean
  impact?: number
  causedBy?: string
}
export interface EdgeOutput {
  id: string
  from: string
  to: string
  rel: string
  props: any
  validFrom: string
  validTo?: string
  recordedAt: string
  supersededBy?: string
  impact?: number
  causedBy?: string
  clock: LogicalClock
}
export const enum ScalingTier {
  H0 = 0,
  H1 = 1,
  H2 = 2,
  H3 = 3,
  H4 = 4,
  H5 = 5,
  H6 = 6
}
export interface ContextPackage {
  nodes: Array<NodeOutput>
  edges: Array<EdgeOutput>
  superNodes: Array<SuperNode>
  tokenEstimate: number
  reasoningPath: string
}
export interface QueryInput {
  from?: string
  to?: string
  rel?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborInput {
  depth?: number
  rel?: string
  rels?: Array<string>
  direction?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborOutput {
  node: NodeOutput
  path: Array<EdgeOutput>
  depth: number
  /**
   * Relevance score for ranked results (hybrid_search): the blended
   * `similarity*(1-alpha) + impact*alpha`. `None` for graph traversal
   * (`neighbors`), which is not relevance-ranked. Kept separate from
   * `node.impact` so the caller still sees the node's true graph-authority
   * signal and can fuse it itself (see ADR--GENESISDB-KIMPACT-AS-SIGNAL).
   */
  score?: number
}
export interface HybridSearchInput {
  queryVector: Array<number>
  k: number
  alpha?: number
  lang?: string
  asOf?: string
  /**
   * Vector collection to search. Defaults to `default`. Query dim is
   * validated against the collection dim (closes the cross-space bug).
   */
  collection?: string
  /**
   * Per-query HNSW `ef_search` override. When `None`, falls back to the
   * engine-global value (`set_index_params`). Higher = better recall, higher
   * latency. Lets a single index serve both high-recall and low-latency
   * callers (the global value can't satisfy both as N grows — see the
   * Recall@500k frontier).
   */
  efSearch?: number
  /**
   * Per-query rerank over-fetch multiplier. When `None`, falls back to the
   * `RERANK_OVERFETCH` default. Only affects collections that carry a rerank
   * sidecar (quantized + rerank); ignored otherwise. Higher = a wider exact
   * re-score pool = better recall on quantized collections, at the cost of
   * more positioned sidecar reads per query. Mirrors the `ef_search` knob.
   */
  oversample?: number
}
export interface DatabaseStatus {
  open: boolean
  readOnly: boolean
  pageCacheMb: number
}
export interface CollectionInfo {
  name: string
  model: string
  dim: number
  metric: string
  quant: string
  count: number
  /** Per-collection default HNSW `ef_search`. `None` ⇒ uses the engine-global default. */
  efSearch?: number
  /** Whether this (quantized) collection keeps an f32 sidecar for exact rerank. */
  rerank: boolean
  /**
   * Ops/credibility (P2c): resident (RAM) bytes held by the exact-f32 rerank
   * sidecar. **≈0 post-P0**: the sidecar is on-disk (`fvec_<name>.bin`) behind a
   * positioned-read `SidecarReader`, not a resident `Vec<f32>`, so its vector
   * data consumes no heap. This field exists to PROVE the P0 RAM win (see
   * docs/RCA--VECTOR-QUANTIZATION.md); a non-zero value here would mean the
   * resident-sidecar regression came back. (`i64` not `u64`: byte counts fit a
   * JS-safe integer and NAPI maps `i64`→JS number; `u64` would force BigInt.)
   */
  sidecarResidentBytes: number
  /**
   * Ops/credibility (P2c): on-disk bytes of the rerank sidecar
   * (`len_rows * dim * 4`), i.e. where the exact-f32 vectors actually live now.
   * `0` when the collection has no sidecar. Shows RAM → disk is where the bytes
   * went, not that they vanished.
   */
  sidecarDiskBytes: number
  /**
   * Ops/credibility (P2c): resident (RAM) bytes of this collection's vector
   * arena (`arena.byte_size()` — f32=4B/elem, SQ8=1B/elem, BQ=1bit/elem).
   * Context for the residency story: this is the RAM the quantized arena costs.
   */
  arenaResidentBytes: number
  /**
   * Ops/credibility (P2c): engine-global async-indexing backlog
   * (`Storage::index_lag()`) — vectors staged into the arena but not yet
   * inserted into HNSW. Not per-collection (one indexing thread serves all
   * collections); the SAME value is repeated on every entry for convenience.
   */
  indexLag: number
}
export interface SyncPeer {
  id: string
  addr: string
  lastSeen: number
  verifyingKey: Array<number>
}
export interface BatchInput {
  nodes: Array<NodeInput>
  edges: Array<EdgeInput>
}
export interface BatchOutput {
  nodes: Array<NodeOutput>
  edges: Array<EdgeOutput>
}
export interface SuperNode {
  clusterId: number
  theme: string
  memberCount: number
  impact: number
  centroid: Array<number>
  timestamp: string
  drift?: number
}
export interface MetaEdge {
  fromCluster: number
  toCluster: number
  weight: number
}
export interface GapSuggestion {
  clusterA: number
  clusterB: number
  similarity: number
  reason: string
}
export declare function engineNameSync(): string
export declare function schemaVersionSync(): number
export declare function versionSync(): string
export declare class GenesisDatabase {
  static open(opts: OpenOptions): GenesisDatabase
  bulkAddNodes(inputs: Array<NodeInput>): Promise<void>
  bulkAddEdges(inputs: Array<EdgeInput>): Promise<void>
  rebuildIndexParallel(): Promise<void>
  addNode(args: NodeInput): Promise<NodeOutput>
  addEdge(args: EdgeInput): Promise<EdgeOutput>
  supersedeNode(id: string, newProps?: any | undefined | null, causedBy?: string | undefined | null): Promise<NodeOutput>
  retractEdge(id: string, at?: string | undefined | null): Promise<EdgeOutput | null>
  retrieveContext(targetId: string, tier: string, budget: number | undefined | null, fuzzy: boolean): Promise<ContextPackage>
  executeHql(query: string): Promise<any>
  hybridSearch(args: HybridSearchInput): Promise<Array<NeighborOutput>>
  neighbors(seed: string, args: NeighborInput): Promise<Array<NeighborOutput>>
  saveState(): Promise<void>
  compact(): Promise<void>
  createCollection(name: string, model: string, dim: number, metric?: string | undefined | null, quant?: string | undefined | null, efSearch?: number | undefined | null, rerank?: boolean | undefined | null): Promise<void>
  listCollections(): Array<CollectionInfo>
  addVector(nodeId: string, collection: string, embedding: Array<number>): Promise<void>
  flushIndex(): Promise<void>
  indexLag(): number
  setLanguageCentroid(lang: string, vector: Array<number>): void
  setIndexParams(efConstruction: number, efSearch: number): void
  detectCommunities(): Promise<void>
  calculateStructuralGaps(): Promise<Array<GapSuggestion>>
  generateMetaGraph(): Promise<void>
  getMetaHistory(clusterId: number): Promise<Array<SuperNode>>
  reconcileState(eventsJson: string): Promise<void>
  /**
   * Anti-entropy source side: JSON of the signed events newer than `from_clock`
   * (sorted by logical time). Pair with `reconcile_state` on the puller.
   */
  eventsSince(fromClock: number): Promise<string>
  semanticVerify(eventJson: string): Promise<boolean>
  proposeConsensus(eventJson: string, signature: Array<number>): Promise<string>
  submitVote(proposalId: string, peerId: string, approve: boolean, signature: Array<number>): Promise<boolean>
  signVote(proposalId: string, approve: boolean): Array<number>
  getLocalPeerId(): string
  getLogicalClock(): number
  getMerkleRoot(): string
  schemaVersionSync(): number
  versionSync(): string
  statusSync(): DatabaseStatus
}
