/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OpenOptions {
  path: string
  pageCacheMb?: number
  readOnly?: boolean
  vectorDim?: number
}
export interface NodeInput {
  id?: string
  labels: Array<string>
  props?: any
  embedding?: Array<number>
  lang?: string
  validFrom?: string
  causedBy?: string
  ttl?: number
}
export interface LogicalClock {
  time: number
  peerId: string
}
export interface NodeOutput {
  id: string
  labels: Array<string>
  props: any
  impact?: number
  embedding?: Array<number>
  lang?: string
  validFrom: string
  validTo?: string
  causedBy?: string
  expiresAt?: string
  clock: LogicalClock
}
export interface EdgeInput {
  id?: string
  from: string
  to: string
  rel: string
  props?: any
  validFrom?: string
  supersede?: boolean
  impact?: number
  causedBy?: string
}
export interface EdgeOutput {
  id: string
  from: string
  to: string
  rel: string
  props: any
  validFrom: string
  validTo?: string
  recordedAt: string
  supersededBy?: string
  impact?: number
  causedBy?: string
  clock: LogicalClock
}
export const enum ScalingTier {
  H0 = 0,
  H1 = 1,
  H2 = 2,
  H3 = 3,
  H4 = 4,
  H5 = 5
}
export interface ContextPackage {
  nodes: Array<NodeOutput>
  edges: Array<EdgeOutput>
  superNodes: Array<SuperNode>
  tokenEstimate: number
  reasoningPath: string
}
export interface QueryInput {
  from?: string
  to?: string
  rel?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborInput {
  depth?: number
  rel?: string
  rels?: Array<string>
  direction?: string
  asOf?: string
  includeInvalid?: boolean
  limit?: number
}
export interface NeighborOutput {
  node: NodeOutput
  path: Array<EdgeOutput>
  depth: number
}
export interface HybridSearchInput {
  queryVector: Array<number>
  k: number
  alpha?: number
  lang?: string
  asOf?: string
}
export interface DatabaseStatus {
  open: boolean
  readOnly: boolean
  pageCacheMb: number
}
export interface SyncPeer {
  id: string
  addr: string
  lastSeen: number
  verifyingKey: Array<number>
}
export interface BatchInput {
  nodes: Array<NodeInput>
  edges: Array<EdgeInput>
}
export interface BatchOutput {
  nodes: Array<NodeOutput>
  edges: Array<EdgeOutput>
}
export interface SuperNode {
  clusterId: number
  theme: string
  memberCount: number
  impact: number
  centroid: Array<number>
  timestamp: string
  drift?: number
}
export interface MetaEdge {
  fromCluster: number
  toCluster: number
  weight: number
}
export interface GapSuggestion {
  clusterA: number
  clusterB: number
  similarity: number
  reason: string
}
export declare function engineNameSync(): string
export declare function schemaVersionSync(): number
export declare class GenesisDatabase {
  static open(opts: OpenOptions): GenesisDatabase
  bulkAddNodes(inputs: Array<NodeInput>): Promise<void>
  bulkAddEdges(inputs: Array<EdgeInput>): Promise<void>
  rebuildIndexParallel(): Promise<void>
  addNode(args: NodeInput): Promise<NodeOutput>
  addEdge(args: EdgeInput): Promise<EdgeOutput>
  supersedeNode(id: string, newProps?: any | undefined | null, causedBy?: string | undefined | null): Promise<NodeOutput>
  retractEdge(id: string, at?: string | undefined | null): Promise<EdgeOutput | null>
  retrieveContext(targetId: string, tier: string, budget: number | undefined | null, fuzzy: boolean): Promise<ContextPackage>
  executeHql(query: string): Promise<any>
  hybridSearch(args: HybridSearchInput): Promise<Array<NeighborOutput>>
  neighbors(seed: string, args: NeighborInput): Promise<Array<NeighborOutput>>
  saveState(): Promise<void>
  compact(): Promise<void>
  setLanguageCentroid(lang: string, vector: Array<number>): void
  detectCommunities(): Promise<void>
  calculateStructuralGaps(): Promise<Array<GapSuggestion>>
  generateMetaGraph(): Promise<void>
  getMetaHistory(clusterId: number): Promise<Array<SuperNode>>
  reconcileState(eventsJson: string): Promise<void>
  semanticVerify(eventJson: string): Promise<boolean>
  proposeConsensus(eventJson: string, signature: Array<number>): Promise<string>
  submitVote(proposalId: string, peerId: string, approve: boolean): Promise<boolean>
  getLocalPeerId(): string
  getLogicalClock(): number
  getMerkleRoot(): string
  schemaVersionSync(): number
  statusSync(): DatabaseStatus
}
