const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 GKS Audit Agent: Starting E2E Verification...');

const auditFile = path.join(__dirname, '../docs/AUDIT--DASHBOARD-E2E.md');
const startTime = new Date().toISOString();

try {
  console.log('📦 Running Playwright Tests...');
  execSync('npx playwright test', { stdio: 'inherit', cwd: __dirname });

  const report = `# AUDIT: Dashboard E2E Verification (Mark XII)

## 📊 Executive Summary
- **Status:** ✅ PASSED
- **Timestamp:** ${startTime}
- **Agent:** Playwright Audit Agent
- **Scope:** GKS Insight Dashboard UI & Connectivity

## 🔍 Verified Components
1. **Layout Integrity:** Sidebar, Header, and Main View correctly rendered.
2. **System Metrics:** Peer ID, Clock, and Node Count cards visible.
3. **Swarm Discovery:** Peer list container present.
4. **Interaction:** Refresh mechanism functional.

## 🛠 Technical Details
- **Test Suite:** Playwright Chromium
- **Target URL:** http://localhost:5175
- **Engine Connection:** Verified (Mock/Live)

---
*Generated by GenesisBlock Audit Agent*
`;

  fs.writeFileSync(auditFile, report);
  console.log(`✅ Audit Complete. Report saved to: ${auditFile}`);

} catch (error) {
  console.error('❌ Audit Failed!');

  const failureReport = `# AUDIT: Dashboard E2E Verification (Mark XII)

## 📊 Executive Summary
- **Status:** ❌ FAILED
- **Timestamp:** ${startTime}
- **Error:** ${error.message}

## 📝 Observations
Tests failed to complete. Ensure the dashboard server can be started and the backend is responsive.

---
*Generated by GenesisBlock Audit Agent*
`;
  fs.writeFileSync(auditFile, failureReport);
  process.exit(1);
}
