/* GenesisBlockDB mobile C ABI — generated from src/ffi.rs. */

#ifndef GENESISDB_H
#define GENESISDB_H

/* DO NOT EDIT: generated by cbindgen from src/ffi.rs. Run scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>

#define STUDIO_SCENE_NODE_CEILING 1000

#define STUDIO_SCENE_EDGE_CEILING 3000

#define STUDIO_SCENE_PAGE_LIMIT 500

/*
 Opaque handle handed back to C. Wraps an `Arc<Storage>` so the engine's
 internal background threads (WAL writer, async HNSW indexer) keep their
 reference-counted owner alive for the handle's whole lifetime.
 */
typedef struct GenesisHandle GenesisHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Open or create a GenesisDB at `path`. Returns an opaque handle, or null on
 error (null/invalid path, or the engine failed to open).

 # Safety
 `path` must be a valid NUL-terminated C string.
 */
GenesisHandle *genesisdb_open(const char *path);

/*
 Close a handle and free its resources. No-op on null. After this call the
 pointer is dangling and must not be reused.

 # Safety
 `handle` must be null or a pointer from [`genesisdb_open`] that has not
 already been closed.
 */
void genesisdb_close(GenesisHandle *handle);

/*
 Add a node. `json_input` is a [`NodeInput`] JSON string; returns a
 [`NodeOutput`] JSON string (free with [`genesisdb_free_string`]) or null on
 error.

 # Safety
 `handle` must be a live handle; `json_input` a valid C string.
 */
const char *genesisdb_add_node(GenesisHandle *handle, const char *json_input);

/*
 Hybrid (vector + lexical) search. `json_input` is a [`HybridSearchInput`]
 JSON string; returns a JSON array of `NeighborOutput` (free with
 [`genesisdb_free_string`]) or null on error.

 # Safety
 `handle` must be a live handle; `json_input` a valid C string.
 */
const char *genesisdb_search(GenesisHandle *handle, const char *json_input);

/*
 Execute an HQL query string. Returns the query result as a JSON string (free
 with [`genesisdb_free_string`]) or null on error.

 # Safety
 `handle` must be a live handle; `hql` a valid C string.
 */
const char *genesisdb_execute_hql(GenesisHandle *handle, const char *hql);

/*
 WP-2.2: execute a versioned Typed Query IR request (`QueryIrRequest`
 JSON, contract `query-ir.v1` — supports `temporal.valid_at` and the
 replica-local `temporal.tx_as_of`). Returns the IR response envelope as a
 JSON string (free with [`genesisdb_free_string`]) or null on error.

 # Safety
 `handle` must be a live handle; `json_input` a valid C string.
 */
const char *genesisdb_execute_query_ir(GenesisHandle *handle, const char *json_input);

/*
 WP-2.2: the Query IR capability manifest (incl. `temporal.history_horizon`
 and the retention profile — ADR I6). Returns a JSON string (free with
 [`genesisdb_free_string`]) or null on error.

 # Safety
 `handle` must be a live handle.
 */
const char *genesisdb_query_ir_capabilities(GenesisHandle *handle);

/*
 Retrieve a tiered context package. `json_input` is a `RetrieveContextInput`
 JSON string: `{ "target_id": "...", "tier": "H1", "budget": null, "fuzzy":
 false }`. Returns a [`crate::ContextPackage`] JSON string (free with
 [`genesisdb_free_string`]) or null on error.

 # Safety
 `handle` must be a live handle; `json_input` a valid C string.
 */
const char *genesisdb_retrieve_context(GenesisHandle *handle, const char *json_input);

/*
 Register a versioned relational schema package encoded as JSON.
 */
const char *genesisdb_register_relational_schema(GenesisHandle *handle, const char *json_input);

/*
 Return the current relational schema package for a namespace.
 */
const char *genesisdb_get_relational_schema(GenesisHandle *handle, const char *namespace_);

/*
 Apply an idempotent U2 mutation batch encoded as JSON.
 */
const char *genesisdb_apply_relational_batch(GenesisHandle *handle, const char *json_input);

/*
 Apply a typed relational mutation batch encoded as JSON.
 */
int32_t genesisdb_apply_relational_rows(GenesisHandle *handle, const char *json_input);

/*
 Execute a bounded relational query encoded as JSON.
 */
const char *genesisdb_query_relational(GenesisHandle *handle, const char *json_input);

/*
 Execute a registered named query encoded as JSON.
 */
const char *genesisdb_execute_named_query(GenesisHandle *handle, const char *json_input);

/*
 Commit one canonical cross-domain transaction encoded as JSON.
 */
const char *genesisdb_commit_transaction(GenesisHandle *handle, const char *json_input);

/*
 Flush the async HNSW index so staged vectors become searchable
 (read-your-write). Returns 0 on success, nonzero on a null/invalid handle or
 a caught panic.

 # Safety
 `handle` must be null or a live handle.
 */
int32_t genesisdb_flush_index(GenesisHandle *handle);

/*
 Free a string previously returned by any `genesisdb_*` function. No-op on
 null. Each returned string must be freed exactly once.

 # Safety
 `s` must be null or a pointer returned by this library and not yet freed.
 */
void genesisdb_free_string(const char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GENESISDB_H */
